<a href="https://colab.research.google.com/github/Hojiakbardevs/Datascience/blob/main/3_2_Ma'lumotlarni_tozalash_va_tayyorlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import sqlite3

In [7]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head(20)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
9,bmw,sedan,101.2,NaN,ohc,four,NaN,23.0,16430.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
11,bmw,sedan,101.2,176.8,ohc,six,121.0,NaN,20970.0
13,bmw,sedan,103.5,189.0,ohc,six,NaN,16.0,30760.0
14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
15,bmw,sedan,110.0,197.0,ohc,six,182.0,NaN,36880.0
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
18,chevrolet,sedan,NaN,158.8,ohc,four,70.0,NaN,6575.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0

In [13]:
df.isnull()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,False,False,False,False,False,False,True,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...
81,False,False,False,False,False,False,False,False,False
82,False,False,True,False,True,False,False,False,False
86,False,False,False,True,False,False,False,True,False
87,False,False,False,False,True,False,False,False,False
88,False,False,False,False,False,False,True,False,False

In [14]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [20]:
nulls = df.isnull().sum()
rows = df.shape[0]
print(nulls/rows *100)

company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [24]:
df.dropna(axis =1)

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [27]:
df.dropna(subset=['price'])

(58, 9)